title = "CloudOn Gitleaks Configuration"

[[rules.allowlists]]
description = "Allowlisted files and paths"
paths = [
    '''gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|bmp)$''',
    '''(go.mod|go.sum)$''',
    '''node_modules''',
    '''package-lock.json''',
    '''infra/migrations/.*''',
    '''.*\.tfstate'''
]
regexes = [
    '''MOCK''',
    '''PLACEHOLDER''',
    '''EXAMPLE''',
    '''SAMPLE''',
    '''TEST'''
]

[[rules]]
    [rules.terraform-state]
    description = "Terraform state files may contain secrets"
    regex = '''(?i)[\w-]*\.tfstate[\w-]*'''
    tags = ["terraform", "config"]

    [rules.aws-access-key]
    description = "AWS Access Key"
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["aws", "credentials"]

    [rules.aws-secret-key]
    description = "AWS Secret Key"
    regex = '''(?i)aws_secret_access_key\s*=\s*[\'\"]*[A-Za-z0-9/+=]{40}[\'\"]*'''
    tags = ["aws", "credentials"]

    [rules.bitbucket-client-id]
    description = "Bitbucket Client ID"
    regex = '''bitbucket(?:_client|_secret)?(?:_key|_id)?[\'\"=\s]*(?:([A-Za-z0-9]{32})|([0-9a-zA-Z]{32}))'''
    tags = ["bitbucket", "credentials"]

    [rules.private-key]
    description = "Private Key"
    regex = '''(?i)-----BEGIN[ A-Z]*PRIVATE KEY'''
    tags = ["key", "private"]

    [rules.password-in-url]
    description = "Password in URL"
    regex = '''[a-zA-Z]{3,10}://[^/\s:@]*?:[^/\s:@]*?@[^/\s:@]*'''
    tags = ["password", "url"]

    [rules.ip-addr]
    description = "IP Address"
    regex = '''(?:^|[^0-9])(?:(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2}))(?:[^0-9]|$)'''
    tags = ["networking", "ip"]
    
    [rules.high-entropy]
    description = "High entropy string"
    regex = '''[0-9a-zA-Z-_!@#$%^&*()]{16,}'''
    entropy = 4.5
    tags = ["entropy", "secret"]

    [rules.confluence-token]
    description = "Confluence API tokens"
    regex = '''(?i)(confluence[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['\"]([a-z0-9=_\-]{32,45})['\"]'''
    tags = ["confluence", "api", "token"]

[allowlist.ip-addr]
regexes = [
    '''(127\.0\.0\.1)''',
    '''(10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})''',
    '''(172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9]{1,3}\.[0-9]{1,3})''',
    '''(192\.168\.[0-9]{1,3}\.[0-9]{1,3})'''
]

[allowlist.high-entropy]
regexes = [
    '''[A-Za-z0-9+/]{64}''',    # Base64 encoded strings
    '''[0-9a-f]{32}''',         # MD5 hashes
    '''[0-9a-f]{40}''',         # SHA1 hashes
    '''[0-9a-f]{64}'''          # SHA256 hashes
]

[[rules]]
id = "confluence-token"
description = "Confluence API tokens"
regex = '''(?i)(confluence[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['\"]([a-z0-9=_\-]{32,45})['\"]'''
tags = ["confluence", "api", "token"]

[global]
file-path = '''(infra)/.*'''
threads = 2
timeout = "10s"
max-file-size = 10485760  # 10MB
show-line-numbers = true
