repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
        files: '(infra|modules)/.*'
        args:
          - --args=-diff
          - --args=-check
      - id: terraform_validate
        files: '(infra|modules)/.*'
      - id: terraform_tflint
        files: '(infra|modules)/.*'
      - id: terraform_tfsec
        files: '(infra|modules)/.*'
      - id: terraform_docs
        files: '(infra|modules)/.*'
        exclude: 'infra/migrations/.*'
        args:
          - '--args=--lockfile=false'
          - '--hook-config=--path-to-file=README.md'
          - '--hook-config=--add-to-existing-file=true'
          - '--hook-config=--create-file-if-not-exist=true'

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        args: ['--config=.gitleaks.toml']


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: detect-aws-credentials
        args:
          - --allow-missing-credentials
    -   id: check-yaml
        args:
          - --allow-multiple-documents
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
        args:
          - --autofix

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        args: ['--in-place']
